version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka-1:
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 101
      KAFKA_ADVERTISED_HOST_NAME: 192.168.2.11
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_MIN_INSYNC_REPLICAS: 2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka-2:
    build: .
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 102
      KAFKA_ADVERTISED_HOST_NAME: 192.168.2.11
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_MIN_INSYNC_REPLICAS: 2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka-3:
    build: .
    ports:
      - "9094:9092"
    environment:
      KAFKA_BROKER_ID: 103
      KAFKA_ADVERTISED_HOST_NAME: 192.168.2.11
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_MIN_INSYNC_REPLICAS: 2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock