global:
  scrape_interval: 10s
  evaluation_interval: 10s
scrape_configs:
- job_name: 'kafka'
  static_configs:
  - targets: ['node-1.{{USERNAME}}.slurm.io:7071', 'node-2.{{USERNAME}}.slurm.io:7071', 'node-3.{{USERNAME}}.slurm.io:7071']
- job_name: 'zookeeper'
  static_configs:
  - targets: ['node-1.{{USERNAME}}.slurm.io:7072', 'node-2.{{USERNAME}}.slurm.io:7072', 'node-3.{{USERNAME}}.slurm.io:7072']
