{
 "title": "Kafka custom dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "burrow: total lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kafka_burrow_total_lag" }
   ]
  },
  {
   "title": "producer: outgoing byte rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_producer_outgoing_byte_total[$__range]))"
    }
   ]
  },
  {
   "title": "consumer: bytes consumed rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_consumer_incoming_byte_total[$__range]))"
    }
   ]
  }
 ]
}