global:
  scrape_interval: 10s
  evaluation_interval: 10s
scrape_configs:
- job_name: 'kafka'
  static_configs:
  - targets: ['node-1.<ваш номер студента>.slurm.io:7071', 'node-2.<ваш номер студента>.slurm.io:7071', 'node-3.<ваш номер студента>.slurm.io:7071']
- job_name: 'zookeeper'
  static_configs:
  - targets: ['node-1.<ваш номер студента>.slurm.io:7072', 'node-2.<ваш номер студента>.slurm.io:7072', 'node-3.<ваш номер студента>.slurm.io:7072']
- job_name: 'burrow-exporter'
  static_configs:
  - targets: ['node-1.<ваш номер студента>.slurm.io:8001']
- job_name: 'producer-exporter'
  static_configs:
  - targets: ['node-1.<ваш номер студента>.slurm.io:7075']
- job_name: 'consumer-exporter'
  static_configs:
  - targets: ['node-1.<ваш номер студента>.slurm.io:7076']
